### ISSUE TITLE
template error while issue view/edit 

### ISSUE THREAD

**Issue by avwifiguy** [MYchaieb/redmine_gc_sync#3]
hi there,

I always get this issue if I try to edit/view an old issue.

```
Started GET "/issues/986" for xxxxxxxxxxxx at 2016-03-24 19:21:24 +0000
Processing by IssuesController#show as HTML
  Parameters: {"id"=>"986"}
  Current user: (id=3)
  Rendered issues/_action_menu.html.erb (3.8ms)
  Rendered issues/show.html.erb within layouts/base (23.7ms)
Completed 500 Internal Server Error in 51ms (ActiveRecord: 4.7ms)

ActionView::Template::Error (Object must be a Date, DateTime or Time object. nil given.):
    69:   end
    70: end %>
    71: <%= render_custom_fields_rows(@issue) %>
    72: <%= call_hook(:view_issues_show_details_bottom, :issue => @issue) %>
    73: </div>
    74:
    75: <% if @issue.description? || @issue.attachments.any? -%>
  lib/redmine/i18n.rb:71:in `format_date'
  plugins/redmine_gc_sync/lib/livrable_date.rb:37:in `view_issues_show_details_bottom'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:96:in `call_hook'
  app/views/issues/show.html.erb:72:in `_app_views_issues_show_html_erb__xxxxxxxxxxxxxxx'
  app/controllers/issues_controller.rb:118:in `block (2 levels) in show'
  app/controllers/issues_controller.rb:115:in `show'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

Thanks in advance for taking time to look at the issue.

**Comment by MYchaieb** [comment]
Hello, 
I Wonder how this is possible. 
Let me explain. 
The error is located at view_issues_show_details_bottom(context = {}) //  File : redmine_gc_sync/lib/livrable_date.rb 
The error says that there is a nil object  given to format_date function. But i already test if the attribute is nil or not. 
what is suggest you to do: 
replace the file redmine_gc_sync/lib/livrable_date.rb  by the one here in the repo. 
if the error exist yet, please send me : 
-Redmine version
-ruby & gem version
- your server OS. 

Hope this will help.
